POST http://localhost:8080/events
content-type: application/json

{
  "Name": "Test event4",
  "Description": "A test event4",
  "Location": "A test location4",
  "DateTime": "2025-08-01T15:30:00.000Z",
  "UserID": 4
}

