POST http://localhost:8080/events
content-type: application/json

{
  "name": "Sample Event",
  "description": "This is a sample event for testing purposes.",
  "date": "2023-10-01T10:00:00Z",
  "location": "Test location",
  "dateTime": "2025-01-01T10:00:00Z",
  }

 